Update packaging.

diff --git a/hhvm/deb/package b/hhvm/deb/package
--- a/hhvm/deb/package
+++ b/hhvm/deb/package
@@ -4,8 +4,10 @@ export PATH=$PATH:/usr/local/bin/
 
 if [ "$#" -le 2 ]; then
     echo "$0 DISTRO_NAME RELEASE VERSION [SOURCE_DIR] [PACKAGE_DIR] [BUILD_DIR] [DEV_PACKAGE_DIR]"
-    echo "for example"
-    echo "$0 ubuntu precise 2.3.0"
+    echo "  for example, stable:"
+    echo "    $0 ubuntu precise 3.3.0-1"
+    echo "  or nightly:"
+    echo "    $0 debian jessie 3.4.0-nightly"
     exit
 fi
 
@@ -14,7 +16,9 @@ DIR=`readlink -m $DIR`
 DISTRO_NAME=$1
 RELEASE=$2
 DISTRO_DIR=$DIR/$RELEASE
-VERSION=$3
+VERSION=$3 # Version of deb we are building, including minor revision (if applicable), e.g., 3.3.2-1
+HHVM_VERSION=`echo $VERSION | cut -d '-' -f 1` # Version without minor revision, e.g., 3.3.2
+STABLE_VERSION=`echo $VERSION | cut -d '.' -f 1-2` # Stable version series, e.g., 3.3
 SOURCE=$4
 SKELETON=$DIR/skeleton
 PACKAGE=$5
@@ -25,6 +29,7 @@ EXTRA_CMAKE_FLAGS=""
 NIGHTLY=false
 DEBUG=false
 DEVONLY=false
+LTS=false
 
 if [ ! -d $DISTRO_DIR ]; then
     echo "directory $DISTRO_DIR doesn't exist"
@@ -37,18 +42,31 @@ if [ -z "$SOURCE" -o ! -d "$SOURCE" ]; then
     SOURCE=`mktemp -d`
 fi
 
-if [ `echo $VERSION | grep '^nightly.*'` ]; then
+if [ `echo $VERSION | grep '.*-nightly.*'` ]; then
     NIGHTLY=true
     echo "Nightly"
 fi
-if [ `echo $VERSION | grep '.*-dev*'` ]; then
+if [ "$NIGHTLY" = true ]; then
+    GIT_TARGET=master
+    PACKAGE_VERSION=$NIGHTLY_DATE~$RELEASE
+else
+    GIT_TARGET=HHVM-$HHVM_VERSION
+    PACKAGE_VERSION=`echo $VERSION | sed -E 's/-(dbg|dev)$//'`~$RELEASE
+    case $STABLE_VERSION in
+        3.3 | 3.6)
+            LTS=true
+            echo "LTS"
+            ;;
+    esac
+fi
+if [ `echo $VERSION | grep '.*-dev$'` ]; then
     DEVONLY=true
-    VERSION=`echo $VERSION | cut -d '-' -f 1`
+    VERSION=`echo $VERSION | sed s/-dev$//`
     echo "Dev only, Debug off"
 fi
 if [ `echo $VERSION | grep '.*-dbg$'` ]; then
     DEBUG=true
-    VERSION=`echo $VERSION | cut -d '-' -f 1`
+    VERSION=`echo $VERSION | sed s/-dbg$//`
     echo "Debug"
 fi
 
@@ -59,16 +77,24 @@ fi
 cd $SOURCE
 if [ ! -d $SOURCE/.git ]; then
     git clone https://github.com/facebook/hhvm.git $SOURCE
+    git checkout $GIT_TARGET
+   
+    # Things that stupidly weren't in the release but we can't re-tag.
+    # Make sure they're on the branch so we can kill them on the next release. 
+    if [ "$RELEASE" = "lucid" ]; then
+      git cherry-pick 774f79f947ef35a73e92d3fe2ce2e4ea83174a58 || true
+    fi
+    if [ "$VERSION" = "3.3.2" ]; then
+      # 3.3.2 fails "make install", whoops...
+      git cherry-pick 97d032ecf4eab6767e333cdcc395c2508a228eb4
+      if [ "$RELEASE" = "jessie" ]; then
+        # jessie changed the way ImageMagick worked, fix got in too late
+        git cherry-pick 26c2a06a09441bbcd2def473fe394865fab6ece8
+      fi
+    fi
 
     if [ "$NIGHTLY" = true ]; then
-        git checkout master
-        perl -pi -e 's/([0-9.]*-dev)/\1+'$NIGHTLY_DATE/ hphp/system/idl/constants.idl.json
-    else
-        git checkout HHVM-$VERSION
-        if ! grep -q $VERSION hphp/system/idl/constants.idl.json; then
-            echo "$VERSION isn't in hphp/system/idl/constants.idl.json"
-            exit
-        fi
+        perl -pi -e 's/([0-9.]*-dev)/\1~nightly.'$NIGHTLY_DATE/ hphp/system/idl/constants.idl.json
     fi
 
     # After the checkout since the submodules might be different between versions
@@ -78,6 +104,7 @@ if [ ! -d $SOURCE/.git ]; then
     mkdir $HEADERS/include
 
     if [ "$RELEASE" = "precise" -o "$RELEASE" = "wheezy" ]; then
+        # These distros don't have a new enough glog
         sudo ln -sf /usr/lib/hhvm/libglog.so.0 /usr/lib/hhvm/libglog.so
         svn checkout http://google-glog.googlecode.com/svn/trunk/ $HEADERS/google-glog
         cd $HEADERS/google-glog
@@ -88,8 +115,8 @@ if [ ! -d $SOURCE/.git ]; then
         sudo cp -d $HEADERS/lib/libglog.so /usr/lib/hhvm/
         sudo cp -d $HEADERS/lib/libglog.so.0 /usr/lib/hhvm/
         sudo cp -d $HEADERS/lib/libglog.so.0.0.0 /usr/lib/hhvm/
-    fi
-    if [ "$RELEASE" = "precise" ]; then
+
+        # They also don't have a new enough jemalloc
         sudo ln -sf /usr/lib/hhvm/libjemalloc.so.1 /usr/lib/hhvm/libjemalloc.so
         cd $HEADERS
         wget http://www.canonware.com/download/jemalloc/jemalloc-3.6.0.tar.bz2
@@ -103,7 +130,13 @@ if [ ! -d $SOURCE/.git ]; then
         sudo cp -d $HEADERS/lib/libjemalloc.so /usr/lib/hhvm/
         sudo cp -d $HEADERS/lib/libjemalloc.so.1 /usr/lib/hhvm/
 
-        EXTRA_CMAKE_FLAGS="-DSTATIC_CXX_LIB=On"
+        # Extra options:
+        #  - Old version of gcc in the base distros mean we need to manually
+        #    install a new gcc, and so should statically link libstdc++ and
+        #    libgcc so users don't have to have the new gcc-base.
+        #  - mcrouter requires boost::context which only exists since boost 1.50
+        #    and these distros have too old a version.
+        EXTRA_CMAKE_FLAGS="-DSTATIC_CXX_LIB=On -DENABLE_MCROUTER=Off"
     fi
 
     if [ -f $DISTRO_DIR/deps ]; then
@@ -116,7 +149,20 @@ if [ ! -d $SOURCE/.git ]; then
     if [ "$DEBUG" = true ]; then
         EXTRA_CMAKE_FLAGS="$EXTRA_CMAKE_FLAGS -DCMAKE_BUILD_TYPE=Debug"
     fi
-    CMAKE_INCLUDE_PATH=$HEADERS/include/ CMAKE_LIBRARY_PATH="/usr/lib/hhvm/" HPHP_HOME=$SOURCE cmake -DCMAKE_INSTALL_PREFIX="/usr" $EXTRA_CMAKE_FLAGS .
+    CMAKE_INCLUDE_PATH=$HEADERS/include/ CMAKE_LIBRARY_PATH="/usr/lib/hhvm/" HPHP_HOME=$SOURCE cmake -Wno-dev -DCMAKE_INSTALL_PREFIX="/usr" $EXTRA_CMAKE_FLAGS .
+
+    if [ -f hphp/runtime/version.h ]; then
+        HPHP_HOME=$SOURCE make version
+        if [ `echo "$VERSION" | sed s/nightly/dev/` != `$SOURCE/hphp/tools/version/version` ]; then
+            echo "$VERSION does not match version.h"
+            exit
+        fi
+    else
+        if ! grep -q $HHVM_VERSION hphp/system/idl/constants.idl.json; then
+            echo "$VERSION isn't in hphp/system/idl/constants.idl.json"
+            exit
+        fi
+    fi
 fi
 
 if [ ! -f $SOURCE/hphp/hhvm/hhvm ]; then
@@ -140,15 +186,12 @@ if [ ! -f $BUILD/usr/bin/hphpize ]; then
 fi
 
 echo "Checking version"
-if [ "$NIGHTLY" = true ]; then
-    $SOURCE/hphp/hhvm/hhvm --version | grep -q $NIGHTLY_DATE
-else
-    $SOURCE/hphp/hhvm/hhvm --version | grep -q $VERSION
-fi
+$SOURCE/hphp/hhvm/hhvm --version | grep -q $HHVM_VERSION
 
 if [ -z "$PACKAGE" -o ! -d "$PACKAGE" ]; then
     PACKAGE=`mktemp -d`
 fi
+FAKEROOT=$PACKAGE/fakeroot.dat
 
 echo "Packaging HHVM in $PACKAGE"
 cd $PACKAGE
@@ -168,14 +211,20 @@ if [ ! -d $PACKAGE/root ]; then
         chmod 755 $PACKAGE/root/usr/bin/hh_client
         chmod 755 $PACKAGE/root/usr/bin/hh_server
     fi
-    mkdir $PACKAGE/root/usr/share/hhvm/hack/
+    if [ -f $SOURCE/hphp/hack/bin/h2tp ]; then
+      cp $SOURCE/hphp/hack/bin/h2tp $PACKAGE/root/usr/bin/
+      chmod 755 $PACKAGE/root/usr/bin/h2tp
+      mkdir -p $PACKAGE/root/usr/share/hhvm/hack/
+      cp -r $SOURCE/hphp/hack/src/h2tp/resources $PACKAGE/root/usr/share/hhvm/hack/hacklib
+    fi
+    mkdir -p $PACKAGE/root/usr/share/hhvm/hack/
     cp -r $SOURCE/hphp/hack/editor-plugins/emacs $PACKAGE/root/usr/share/hhvm/hack/
-    cp -r $SOURCE/hphp/hack/editor-plugins/vim $PACKAGE/root/usr/share/hhvm/hack/
+
     if [ "$NIGHTLY" = true ]; then
         perl -pi -e "s/Conflicts: .*\n//" $PACKAGE/root/DEBIAN/control
         perl -pi -e "s/Provides: .*\n//" $PACKAGE/root/DEBIAN/control
         perl -pi -e "s/Replaces: .*\n//" $PACKAGE/root/DEBIAN/control
-        perl -pi -e "s/Version:.*/Version: $NIGHTLY_DATE~$RELEASE/" $PACKAGE/root/DEBIAN/control
+        perl -pi -e "s/Version:.*/Version: $PACKAGE_VERSION/" $PACKAGE/root/DEBIAN/control
         if [ "$DEBUG" = true ]; then
             perl -pi -e "s/Package: hhvm/Package: hhvm-nightly-dbg\nConflicts: hhvm, hhvm-nightly, hhvm-dbg\nProvides: hhvm\nReplaces: hhvm, hhvm-nightly, hhvm-dbg/" $PACKAGE/root/DEBIAN/control
         else
@@ -188,20 +237,21 @@ if [ ! -d $PACKAGE/root ]; then
             perl -pi -e "s/Replaces: .*\n//" $PACKAGE/root/DEBIAN/control
             perl -pi -e "s/Package: hhvm/Package: hhvm-dbg\nConflicts: hhvm\nProvides: hhvm\nReplaces: hhvm/" $PACKAGE/root/DEBIAN/control
         fi
-        perl -pi -e "s/Version:.*/Version: $VERSION~$RELEASE/" $PACKAGE/root/DEBIAN/control
+        perl -pi -e "s/Version:.*/Version: $PACKAGE_VERSION/" $PACKAGE/root/DEBIAN/control
     fi
-    sudo chown -R root:root $PACKAGE/root
-    sudo chown -R www-data:www-data $PACKAGE/root/var/log/hhvm/
-    sudo chown -R www-data:www-data $PACKAGE/root/var/run/hhvm/
+    fakeroot -s $FAKEROOT chown -R root:root $PACKAGE/root
+    fakeroot -s $FAKEROOT -i $FAKEROOT chown -R www-data:www-data $PACKAGE/root/var/log/hhvm/
+    fakeroot -s $FAKEROOT -i $FAKEROOT chown -R www-data:www-data $PACKAGE/root/var/run/hhvm/
     echo "finished creating hhvm package contents"
 fi
 
-dpkg -b $PACKAGE/root/ hhvm_${VERSION}_amd64.deb
-dpkg-sig -k 452A652F --sign builder $PACKAGE/hhvm_${VERSION}_amd64.deb
+fakeroot -i $FAKEROOT dpkg -b $PACKAGE/root/ hhvm_${PACKAGE_VERSION}_amd64.deb
+dpkg-sig -k 452A652F --sign builder $PACKAGE/hhvm_${PACKAGE_VERSION}_amd64.deb
 
 if [ -z "$DPACKAGE" -o ! -d "$DPACKAGE" ]; then
     DPACKAGE=`mktemp -d`
 fi
+FAKEROOT=$DPACKAGE/fakeroot.dat
 
 if [ "$DEBUG" = false ]; then
     echo "Packaging dev in $DPACKAGE"
@@ -226,48 +276,59 @@ if [ "$DEBUG" = false ]; then
         fi
         cp -r $BUILD/usr/bin/hphpize $DPACKAGE/root/usr/bin/
         chmod 755 $DPACKAGE/root/usr/bin/hphpize
+        perl -pi -e "s/Version:.*/Version: $PACKAGE_VERSION/" $DPACKAGE/root/DEBIAN/control
         if [ "$NIGHTLY" = true ]; then
-            perl -pi -e "s/Version:.*/Version: $NIGHTLY_DATE~$RELEASE/" $DPACKAGE/root/DEBIAN/control
             perl -pi -e "s/Package: hhvm-dev/Package: hhvm-dev-nightly\nConflicts: hhvm-dev\nProvides: hhvm-dev\nReplaces: hhvm-dev/" $DPACKAGE/root/DEBIAN/control
-        else
-            perl -pi -e "s/Version:.*/Version: $VERSION~$RELEASE/" $DPACKAGE/root/DEBIAN/control
         fi
-        sudo chown -R root:root $DPACKAGE/root
+        fakeroot -s $FAKEROOT chown -R root:root $DPACKAGE/root
         echo "finished creating dev package contents"
     fi
 
-    dpkg -b $DPACKAGE/root/ hhvm_dev_${VERSION}_amd64.deb
-    dpkg-sig -k 452A652F --sign builder $DPACKAGE/hhvm_dev_${VERSION}_amd64.deb
+    fakeroot -i $FAKEROOT dpkg -b $DPACKAGE/root/ hhvm_dev_${PACKAGE_VERSION}_amd64.deb
+    dpkg-sig -k 452A652F --sign builder $DPACKAGE/hhvm_dev_${PACKAGE_VERSION}_amd64.deb
 fi
 
-SSH_KEY=/home/ptarjan/.ssh/id_rsa_phraseless
+SSH_KEY=$HOME/.ssh/id_rsa_phraseless
+STAGING=/var/tmp/staging/$DISTRO_NAME/
 
-rsync -avz -e "ssh -i $SSH_KEY" hiphop@dl.hhvm.com:data/$DISTRO_NAME/ $PACKAGE/staging/ || true
+mkdir -p $STAGING
+rsync --delete -av -e "ssh -i $SSH_KEY" hiphop@dl.hhvm.com:data/$DISTRO_NAME/ $STAGING || true
 # do it twice since it takes so long something else might have pushed
-rsync -avz -e "ssh -i $SSH_KEY" hiphop@dl.hhvm.com:data/$DISTRO_NAME/ $PACKAGE/staging/
+rsync --delete -av -e "ssh -i $SSH_KEY" hiphop@dl.hhvm.com:data/$DISTRO_NAME/ $STAGING
 
-cd $PACKAGE/staging
+REPREPRO="reprepro --keepunreferencedfiles --keepunusednewfiles includedeb"
+
+cd $STAGING
 if [ "$DEVONLY" = true ]; then
     # these take up too much space
-    if [ "$NIGHTLY" = true]; then
-        rm pool/main/h/hhvm-${VERSION}/*dev*${RELEASE}*.deb || true
+    if [ "$NIGHTLY" = true ]; then
+        rm pool/main/h/hhvm-dev-nightly/*dev*${RELEASE}*.deb || true
     fi
     echo "repreproing dev package"
-    reprepro includedeb $RELEASE $DPACKAGE/hhvm_dev_${VERSION}_amd64.deb
+    $REPREPRO $RELEASE $DPACKAGE/hhvm_dev_${PACKAGE_VERSION}_amd64.deb
+    if [ "$LTS" = true ]; then
+        $REPREPRO $RELEASE-lts-$STABLE_VERSION $DPACKAGE/hhvm_dev_${PACKAGE_VERSION}_amd64.deb
+    fi
 else
     if [ "$NIGHTLY" = true ]; then
         if [ "$DEBUG" = true ]; then
-            rm pool/main/h/hhvm-${VERSION}-dbg/*${RELEASE}*.deb || true
+            rm pool/main/h/hhvm-nightly-dbg/*${RELEASE}*.deb || true
         else
-            rm pool/main/h/hhvm-${VERSION}/*${RELEASE}*.deb || true
+            rm pool/main/h/hhvm-nightly/*${RELEASE}*.deb || true
         fi
     fi
 
     #TODO figure out how the -b options works
-    reprepro includedeb $RELEASE $PACKAGE/hhvm_${VERSION}_amd64.deb
+    $REPREPRO $RELEASE $PACKAGE/hhvm_${PACKAGE_VERSION}_amd64.deb
+    if [ "$LTS" = true ]; then
+        $REPREPRO $RELEASE-lts-$STABLE_VERSION $PACKAGE/hhvm_${PACKAGE_VERSION}_amd64.deb
+    fi
     if [ "$DEBUG" = false ]; then
         echo "repreproing dev package"
-        reprepro includedeb $RELEASE $DPACKAGE/hhvm_dev_${VERSION}_amd64.deb
+        $REPREPRO $RELEASE $DPACKAGE/hhvm_dev_${PACKAGE_VERSION}_amd64.deb
+        if [ "$LTS" = true ]; then
+            $REPREPRO $RELEASE-lts-$STABLE_VERSION $DPACKAGE/hhvm_dev_${PACKAGE_VERSION}_amd64.deb
+        fi
     fi
 fi
 cd -
@@ -278,9 +339,15 @@ if [ "$NIGHTLY" = true ]; then
     RSYNC_OPTS="--delete"
 fi
 
-rsync $RSYNC_OPTS -avz -e "ssh -i $SSH_KEY" $PACKAGE/staging/ hiphop@dl.hhvm.com:data/$DISTRO_NAME/
+rsync $RSYNC_OPTS -av -e "ssh -i $SSH_KEY" $STAGING hiphop@dl.hhvm.com:data/$DISTRO_NAME/
 ssh -i $SSH_KEY hiphop@dl.hhvm.com "/home/hiphop/trigger-hiphop"
 
 # cleanup
 rm -rf $HEADERS $SOURCE
-sudo rm -rf $PACKAGE $BUILD $DPACKAGE
+rm -rf $PACKAGE $BUILD $DPACKAGE
+
+if [ "$NIGHTLY" = true -a "$DEBUG" = false ]; then
+    echo "Pinging FB build tracker"
+    curl "https://our.intern.facebook.com/intern/hhvm/ossbuildping/?distro=$RELEASE"
+    echo
+fi
